### PR TITLE
added permalinks to bottom pages of beginner guide for "next sections"

### PR DESCRIPTION
**Pull request by jmarlena**
Followed Nick-Tallguy's suggestion of adding manual permalinks to the next sections under the heading "Moving Forward." Open to renaming or reorganizing the links and other semantic changes as others see fit.

### CODE REVIEW

**Comment by pyrog** [comment]
Thanks all but this job is missing in all other languages. See #303

**Comment by pyrog** [comment]
There are another issues with adding manually the "Moving forward" section:
* it's a big job to maintain this
* you could make a mistake<br/>(see **Surveying with GPS** in **[Surveying with Field Papers](http://learnosm.org/en/beginner/field-papers/)**. This is a back link :wink:)
* In **[All chapters](http://learnosm.org/en/beginner/all-chapters/)** you have all the guide in one page:<br/> Is there any sense to add links to next chapter ?

Another point: Visually, it's impossible to distinguish links to a chapter in the same guide of links to chapters of other guides:

Example: http://learnosm.org/en/beginner/start-osm/#moving-forward
[moving-forward](http://learnosm.org/en/beginner/start-osm/#moving-forward)

**Comment by Nick-Tallguy** [comment]
@pyrog I agree we need to put some more thought into this.   

*  **All Chapters**  I was probably being a bit 'thick' when I first read my way though the site, but I started with 'Introduction', then read 'OpenStreetMap.org' and continued working my way through the 'chapters'. I eventually got to **All Chapters** after I'd read all of the others. At the end of each of the previous chapters I muttered about a system where I had to scroll all the way back up to the top in order to find the link for the next chapter. I was even more '**!!!**' when I found **All Chapters** at the bottom of the list & realised that it would have made my life easier if I'd found it earlier.   

I think we need to discuss & chose a system that makes more sense. **All Chapters** is only a good idea if it is at the top of the list & perhaps contains an opening paragraph explaining that it contains all of the other chapters. Another thought - combine all of the Beginners section into one file - effectively what we've got now with **All Chapters** and then have different headings on the navigation bar, with the combined file having a Table of Contents with clickable links to the different sections within it. 

I started the links when I started the **Remote, Armchair & Mapathon** series, because there are parts of the beginner section that you need to use. If we made the links more descriptive, it should help.

Another alternative is to create a **Whole site listing** page, but have headings such as;  
+  **Remote, Armchair & Mapathon** & below this heading is a list of suggested 'chapters' for the reader to work through.  
+  **Beginners Guide** - again a list of chapters, some of which will be duplicates of the previous heading.  
+  **Workshop** - list of items / chapters depending on location.  
+  **Using the data** (or similar) & a list of the subjects such as QGIS  
+  **Task Owners - creating tasks on Task manager** - *this still needs writing!*

I haven't completely got my thoughts in order as to how I would like the site to be. But having taken an interest in it, I've realised that some subjects, such as the **Getting started with the iD editor** were sitting in the sidelines with no visible link to them. You only find them if you know they are there in the first place. Somebody started work on a google type search for the whole site, but that never seemed to come to fruition for some reason. 

Sorry, very long and rambling!  I'd like the time to create a few alternatives as forks / branches so that they could be viewed, considered & a consensus agreed as to how the site should be laid out. I'm willing to help now, or in the future, but my knowledge on the subject is not great so I would need to carry out some learning myself first.

**Comment by pyrog** [comment]
> Another thought - combine all of the Beginners section into one file - effectively what we've got now with All Chapters and then have different headings on the navigation bar, with the combined file having a Table of Contents with clickable links to the different sections within it.

We have a similar discussion (in french) with althio :smile: 
One file by guide with an automated TOC could be simpler, but with big guides the file will be… (too) big?

Penflip could help us to test some ideas, concepts… (manage [books an single page documents](https://www.penflip.com/Penflip/help/blob/master/getting-started/ProjectTypes.txt), generate [epub, pdf](https://www.penflip.com/Penflip/help/blob/master/publishing/publishing-overview.md)…)

> Somebody started work on a google type search for the whole site

The actual search engine is mysterious and seem unusable.
Of course, we could use Google search (or others) but what about offline uses?
Some eBook readers could index files and all have a search engine, generate a TOC…
But how peoples use learns guides?

There is also some Jekyll plugins that index static sites.

> Task Owners - creating tasks on Task manager 

What is the goal of learnosm?
* learn how to use OpenStreetMap and create "maps"
* learn how to use HOT tools

> I'd like the time to create a few alternatives as forks / branches so that they could be viewed, considered & a consensus agreed as to how the site should be laid out.

That the goal of "my" sandbox :smile: 

----
That's all for this night, I need to sleep :wink: 
And we could discuss on IRC or in audio/video with Skype…

**Pull request merged**
