### PR TITLE
fixed anchor for non-latin scripts

### PR DESCRIPTION
**Pull request by Andygol**

### CODE REVIEW

**Comment by Andygol** [comment]
Here is amendment for specifying anchors for non-latin scripts LTR and RTL writing

<http://127.0.0.1:4000/fa/josm/start-josm/#یادگیری-ترسیم‌های-اولیه-در-josm> 👇 
image

and <http://127.0.0.1:4000/uk/josm/start-josm/#точки-лінії-та-фігури-полігони> 👇 
image

/cc @Nick-Tallguy

**Comment by Nick-Tallguy** [comment]
Thanks Andrew,

Sorry to have caused you the extra work.

I hope to be on my laptop later tonight and I'll do the pull then.

Regards

Nick (OSM=Tallguy)
my phone is responsible for any spelling mistakes!

**Comment by Nick-Tallguy** [comment]
Thanks @Andygol and @althio - merge done and all working well now, including the right to left pages. I'm just adding the ru and uk modules that were in the initial pull request.

**Comment by Nick-Tallguy** [comment]
I've checked all the uk modules that were included, and they were already in learnosm. The same with the other ru modules. 

I think that is everything now, thanks.

**Comment by althio** [comment]
Cool I like it! Thanks @Andygol and @Nick-Tallguy 😄

**Pull request merged**
