### PR TITLE
remove downloadable docs and references to them - branch Iss568

### PR DESCRIPTION
**Pull request by Nick-Tallguy**
#568 refers

@michael63-osm - leaving this as a pull request at the moment - not sure if you wish to check this, or implement it at a time of your choosing. Let me know your thoughts please. 

I have a complete copy of the site before this pull request and am checking files individually when I get the chance.

### CODE REVIEW

**Comment by Nick-Tallguy** [comment]
I've checked through all en versions of files, and updated any files of any language that this disclosed as needing editing.

**Comment by Nick-Tallguy** [comment]
All should now be okay

**Comment by Nick-Tallguy** [comment]
Hi @michael63-osm , coiuld this be merged soon as the conflicts are starting to build and cause me problems. If you are short of time and you would like it, I can merge or otherwise push this through.

Regards

Nick

**Comment by Nick-Tallguy** [comment]
sorry @michael63-osm - didn't intend to merge this, was just working to clear the conflicts

**Comment by michael63-osm** [comment]
@Nick-Tallguy  for any matters where you need my action or review: my employer sent me to a conference this week so I cannot do anything before the next weekend

**Pull request merged**
