### PR TITLE
fix images_jp folder and improve translation on Japanese

### PR DESCRIPTION
**Pull request by nyampire**
I put some improvements on Japanese translation.

1. Forwarding to current English master from before.
2. Adding new translation targets from master to Japanese. (mobile and TaskManager)
3. Moving the images for jp contents to images/jp folder.

### CODE REVIEW

**Comment by althio** [comment]
@nyampire That is an impressive work. Thank you!
Is there something you want us to review or verify in particular or are you confident enough that we can go ahead and merge?

**Comment by nyampire** [comment]
I have checked, but not tested.
If you could, please test if the title lists are correctly displayed. (on mobile and coodination pages)

**Comment by althio** [comment]
I think we can merge.
If corrections are needed we will work on new issues and pull requests.

**Comment by nyampire** [comment]
Thank you. I've confirmed the site and they are OK.
I'll proceed my translation work as another issue/PR.

**Pull request merged**
