### PR TITLE
Merge pull request #1 from hotosm/gh-pages

### PR DESCRIPTION
**Pull request by ghost**
Update from original

### CODE REVIEW

**Comment by Nick-Tallguy** [comment]
Hi, can you clarify what this pull request does please - appears to alter just about every file in the repository?

**Comment by Nick-Tallguy** [comment]
I'm closing this pull request - not actioned. I've had a quick glance &;  
+  Contributor unknown,   
+  No reply from contributor (so far)  
+  No comments giving a clue as to the aim of the changes
+  Very major change with hundreds of files changed,  
+ I think (can't be sure) that someone has attempted to update their fork, and 'done it the wrong way' so all the changes are here - honest error, but we don't want to incorporate this without more info,  
+  We can always open it later & sort it out if needed - when more info is available.

**Comment by althio** [comment]
Yes, most likely an error with a pull request the wrong way.

**Comment by Nick-Tallguy** [comment]
@althio I've been through the branches for the site & deleted them all - they are easy to recreate if needed. When I first started updating the site I had a problem because of the redundant branches, and I'm hoping that keeping them trimmed down to the necessities saves someone else the problems - that may have been the problem on this pull request. 
I know it caused me a real headache when I first started.

**Pull request closed without merging**
