### PR TITLE
Patch kiswahili

### PR DESCRIPTION
**Pull request by althio**

### CODE REVIEW

**Comment by althio** [comment]
@Nick-Tallguy please review

**Comment by althio** [comment]
I didn't intended to make the change from `jp` to `ja` so soon.
It should have been `jp` still in this commit. Sorry, my bad.
Thanks for your careful review!

I opened the new issue #362 to keep track of this for future reference but didn't want to pull that right now.

**Comment by Nick-Tallguy** [comment]
No problem. I won't be able to do any more this morning & not sure about this evening. Suggest we leave   bi to id for another day.

**Comment by althio** [comment]
Agreed.
Merging, follow overall status at #362.

**Comment by althio** [comment]
Not working for japanese, revert.

**Pull request merged**
