### PR TITLE
Uk translate

### PR DESCRIPTION
**Pull request by Andygol**
Beginning of Ukrainian translation

### CODE REVIEW

**Comment by althio** [comment]
Hi @Andygol

Thank you for your hard work on this ukrainian translation.
Let us know if we can help you or when you want us to merge.

**Comment by Andygol** [comment]
Hi @althio 
thanks for your attention. :smile: 

I have a plan to translate/update beginers section. I made this [translation](http://blog.i.ua/community/3763/766253/) early before the appearance LearnOSM

I want to consult the best way to do:
* Complete the translation and then make merge

 or
* Do merge after each commit after the translation the next section?

What do you think about this?

**Comment by althio** [comment]
@Andygol 
> Complete the translation and then make merge
or
Do merge after each commit after the translation the next section?

I do not have a strong opinion. We can do as you prefer. Just mention it here when you think it is the good time to merge.

**Comment by Andygol** [comment]
> Just mention it here when you think it is the good time to merge.

@althio Ok, I'll notify, when I finish translation and it will be ready for merging

**Comment by Andygol** [comment]
Hey @althio!
I just finished translation of the Beginner Guide into Ukrainian. May you merge my pull request into `gh-page`  branch. It containing along with Ukrainian translation some fixes  3360cda of the English text.

**Comment by althio** [comment]
Many thanks for the translation and the fixes!

**Pull request merged**
