### PR TITLE
Added Vespucci Editor for mobile mapping

### PR DESCRIPTION
**Pull request by mmlmendoza**
I've noticed there's no guide for using Vespucci in the learnosm site. Made one since Vespucci is a good app for mobile mapping in Android and it's what I also use.

### CODE REVIEW

**Comment by Nick-Tallguy** [comment]
Hi mamon,

I'm travelling with limited internet access but hoping to look at your hard
work in the next few days.

Nick
my phone is responsible for any spelling mistakes!

**Comment by Nick-Tallguy** [comment]
Hi,
I've had a quick look through, and it's looking good, but can I get you to make a few changes please. Our target audience is often in parts of the world with poor internet access, and we therefore have an image restriction of 800 pixels on the longest edge for any images. A quick look shows many of your images are far larger than this, and will slow or stop the site considerably if internet access is poor. Please reduce the images to 800px along longest edge.  

_posts/en/0900-07-20-vespucci_en.md  
Please make the following amendments;  
line 49, add a space after the )  
line 103, I think the last sentence should read "A new node will be added in the selected location."  
line 124, I think this should read "Select what you want to redo."  

Thanks for working on this.

Regards

Nick

**Comment by mmlmendoza** [comment]
> Hi,
> I've had a quick look through, and it's looking good, but can I get you to make a few changes please. Our target audience is often in parts of the world with poor internet access, and we therefore have an image restriction of 800 pixels on the longest edge for any images. A quick look shows many of your images are far larger than this, and will slow or stop the site considerably if internet access is poor. Please reduce the images to 800px along longest edge.
> 
> _posts/en/0900-07-20-vespucci_en.md
> Please make the following amendments;
> line 49, add a space after the )
> line 103, I think the last sentence should read "A new node will be added in the selected location."
> line 124, I think this should read "Select what you want to redo."
> 
> Thanks for working on this.
> 
> Regards
> 
> Nick

Hi! I've already edited my work based on your comments. I've already updated the _posts/en/0900-07-20-vespucci_en.md and reduced the dimensions of all the images. 

This is my first contribution on GitHub so thank you for checking!

**Comment by Nick-Tallguy** [comment]
Hi @mmlmendoza I've pulled your work into the site, but at the moment the images are not displaying. I think you have named the images *.PNG, but in the .md file you have referenced them as .png  - I can't work on this at the moment, but may have internet access later today or tomorrow. If you are able to correct this, that would be good, if not I'll work on it when I can.

Regards

Nick

**Comment by mmlmendoza** [comment]
Hi!

Thank you for notifying me. I've already edited the .md file and issued a
new pull request.

**Pull request merged**
