### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by althio**
add links to conventions and guidelines for contributing

### CODE REVIEW

**Comment by Nick-Tallguy** [comment]
@althio - Looks pretty good to me. 

Not sure if we should go with the system outlined for the image filing though. I think @pyrog is advocating something slightly different & I'm keen to hear his advice.  

At the moment we seem to be part way between:  
1.  /images/language (2digit)/section/file/filename
2.  /images/language/section/file/complicated filename to do with filename, language (de_beg_02_start-osm_export.png)  
3.  the system outlined here https://github.com/hotosm/learnosm/wiki/Images-guidelines-beta  
4.  images/language/filename/simpleimagename such as iD_01.png

 1/. I don't like because of the /section/ folder - one of the advantages we are trying to achieve is the ability to quickly create a new 'index' so that a section appears elsewhere. If we have a /section/ folder we defeat that.  
 2/. Just makes my eyes go blurry trying to find anything - sorry, simple as that!   
 3/. Blurry eyes, plus we will end up with too many images in one folder for ease of locating.  
 4/. Just looks simple while avoiding the problems of 1, 2 & 3. My example above would be:
    /images/en/remote/iD_01.png

If we're going to alter the image storage system, perhaps now is the time to update the documentation - which is wrong anyway according to what we've got. 

The wiki reads as if it was aimed at converting google docs into markdown docs for creating the site. Although interested it may be time to do some drastic altering. Personally when I'm adding images I'm creating them using a variety of steps, avoiding having any writing in them at all (so they can be used in all language versions) and using Gimp to reduce them to 520px - there is discussion in one of the issues about this and I think the consensus I would go for is 'use whatever software you find easiest so you end up with an image of no more than 520px'

If we update the wiki &/or contributing.md now so it shows the system we are aiming for, we will know what to do in the future, and hopefully not have conflicting advice.

**Comment by pyrog** [comment]
In "my" sandbox, I use only one image folder but there will be to many images.
I thought we could use a folder by guide, but I like **4/.**

But I prefer to avoid language subfolder and use a language extension (See [Content negotiation](http://httpd.apache.org/docs/2.4/en/content-negotiation.html#naming) concept).

`/images/remote/iD_01.png` for the english version
`/images/remote/iD_01.fr.png`

If an image is _"neutral language"_ (like a picture of a mapper using a gps receiver) all "translations" use the "english" image (`/images/gps/mapper-holding-a-gps-receiver.png`)

But if the image contain important text or have a **cultural meaning**, for example french translation of a chapter use `/images/field-papers/website.fr.png` if french translators provide it, otherwise they use the "english" version.

See [Internationalization and localization of images](http://www.cbstrad.com/blog.versdautreshorizons/2011/04/20/internationalization-and-localization-of-images/).

**Comment by althio** [comment]
I agree it is only a feeble attempt to document the current (and partly
outdated) guidelines and publicise them.

I am very happy that it triggers such an inspiring discussion on image
filing. It appears certainly to be the messy part for the time being. The
wiki is only labeled "guidelines-beta" so it clearly implies that everyone
is aware it is not finalised yet.

I would like to merge this PR then, as a first step for the current and any
future documentation.

@Nick-Tallguy @pyrog
Could you please copy/paste your insightful comments on image filing into
an new issue or an outstanding issue, such as #94 or #113?

**Comment by Nick-Tallguy** [comment]
@althio sorry I hijacked this, but I think we have a working resolution on a filing system - as per pyrog's suggestion. I've pasted it into #306

**Pull request merged**
