### PR TITLE
Korean translation for first 3 documents

### PR DESCRIPTION
**Pull request by depth221**
I translated "0200-12-31-beginner.md", "0200-12-29-introduction.md", and "0200-12-27-start-osm.md", but could't find "1-essential_setup.txt".
Is there something I should work?

### CODE REVIEW

**Comment by michael63-osm** [comment]
Unfortunately I am currently travelling with very occasional internet access. I will take care of this next week.

Regards
Michael

**Comment by matkoniecz** [comment]
ping @michael63-osm

**Comment by LaoshuBaby** [comment]
ping @michael63-osm

**Comment by michael63-osm** [comment]
@LaoshuBaby I am not quite sure what you want to tell me with your ping.

**Comment by michael63-osm** [comment]
Sorry, this has just gone out of my scope. The Korean translations have been available on LearnOSM since mid November 2018. Closing this issue now

**Pull request closed without merging**
