### PR TITLE
Should make searches for buildings, walls, barriers etc possible 

### PR DESCRIPTION
**Pull request by Nick-Tallguy**
@althio - Ben, I'd be grateful if you could have a quick look in case I've made a stupid mistake. I think it's okay, and it displays locally on my machine okay.

This splits the remote section roughly in half (it was getting too big!). By naming the second file with the words buildings walls barriers in the name, it makes them searchable on the site. Also adds a section index to the file, so that internal navigation on that file is easier.

Renaming the files in the co-ordination section merely alters the order in the index, so it should appear more logical. 
selection_079

### CODE REVIEW

**Comment by althio** [comment]
My apologies @Nick-Tallguy I merged something in one of the files you renamed and that creates a conflict for your pull request.
Do you per chance know how to follow the changes (rebase?).

**Comment by Nick-Tallguy** [comment]
@althio I'll give it a try

**Comment by Nick-Tallguy** [comment]
@althio I've updated my repo, and displayed locally before submitting the pull request again - the potlatch 2 material should be unchanged and this should alter all the file names ok.  Thanks for reviewing.

**Comment by althio** [comment]
Thanks @Nick-Tallguy and sorry for the trouble.
Everything seems fine to me. I'll merge, please review one more time on the live instance that everything is according to your idea.

**Pull request merged**
