### PR TITLE
Improvements for RTL

### PR DESCRIPTION
**Pull request by iriman**
issue #618

### CODE REVIEW

**Comment by michael63-osm** [comment]
@iriman   Thank you for your work here. It might take a little bit before we can merge this as we have a staging site (see details on https://learnosm.org/en/contribute/translator/) where we have two more rtl languages, Arabic and Hebrew, which have to be considered apart from Farsi. Additionally, we do not edit foreign language versions of our documents here but automatically pull the translations from Transifex. Any additional modifications would have to be performed by scripting during the pull process.

Getting all this under one hood needs a few preparations and checks. But I hope to get this done within this week.

**Comment by iriman** [comment]
Very good, please let me know if there was any problem regarding rtl.

**Comment by iriman** [comment]
I dig into this a bit more. We can avoid changing anything on transifex side, instead use liquid to put a condition for the rtl languages to detect rtl.  Please take a look at [gh-pages...iriman:newrtl](https://github.com/hotosm/learnosm/compare/gh-pages...iriman:newrtl)

I also renamed direction-dependent css rules to be more meaningful in both rtl and ltr.

Totally I guess this is a much cleaner way. 

In case if not decided yet, I would like to suggest this approach. I can send a new PR or force push here.

**Comment by michael63-osm** [comment]
As you noticed I pulled your request on the staging site. Seems to work fine. And issuing pull requests on the staging site is our preferred way as we can try things out there without disrupting the main site. I will pull these changes over to the main site this weekend. Thanks again for your work.

**Pull request closed without merging**
