### PR TITLE
Update 0200-12-03-moving-forward.md

### PR DESCRIPTION
**Pull request by nuruk**
Already translated.

### CODE REVIEW

**Comment by nuruk** [comment]
This file already translated.

**Comment by Nick-Tallguy** [comment]
I've added some more files in the mobile-mapping section, ready for translation. If there are any other modules you would like inserted soon, let me know.

Keep up the good work, thanks.

**Comment by Nick-Tallguy** [comment]
Also, please don't delete the header info - it's needed to make it display. Thanks

**Comment by nuruk** [comment]
okey that mistake only happen to two files but other three files are good.
On Sep 29, 2015 6:04 PM, "Nick Allen (OSM = Tallguy)" <
notifications@github.com> wrote:
>
> Also, please don't delete the header info - it's needed to make it
display. Thanks

**Comment by Nick-Tallguy** [comment]
No problem.  All sorted out.

Nick
(OSM=Tallguy)

dodgy didgits as using a phone with a spell chequer.

Humanitarian OpenStreetMap Team Member

**Pull request merged**
