### PR TITLE
changing language code from jp to ja

### PR DESCRIPTION
**Pull request by Nick-Tallguy**
Implement this at the same time as the reorder of the language list. 

I think I've covered all of the changes, but it's always possible there is an internal link somewhere I've missed.

### CODE REVIEW

**Comment by althio** [comment]
@Nick-Tallguy Thanks for all the changes.
What do we do with /images/jp/ and all the links? :'(

**Comment by Nick-Tallguy** [comment]
The images and links from the files to them should all still work okay.  When the images are reorganised they can be put in a new folder with the correct name.

**Comment by Nick-Tallguy** [comment]
@althio just to clarify.  This can be merged now. The documents have all been changed for the Japanese change of code. But within a few seconds you also need to merge your change in which 'jp' becomes 'ja'.  

It's the documents that point to the images, so the images can currently remain in their old folder. When someone gets the chance to 'tidy' in line with #306 the images can be moved to a new folder, and renamed to align with the requirements of #306 

Hope this makes sense

**Comment by althio** [comment]
Excellent @Nick-Tallguy 
Merging, follow overall status at #362.

**Comment by althio** [comment]
Not working for japanese, revert.

**Pull request merged**
