### PR TITLE
Update mapping with BasicAirData GPSLogger v3.0

### PR DESCRIPTION
**Pull request by GrazianoCapelli**
Hello LearnOSM team,
Today we updated BasicAirData GPSLogger to the v3.0 (https://github.com/BasicAirData/GPSLogger).
The new release brings many interesting features for the users and some news on user interface.
For example we introduced a new bottom bar, strongly inspired by audio recorders, with the hope to give users a more friendly interface.

I updated article and images, describing the basic usage with the new UI.

I added also the GIMP format of the image that contains some text, in case some translators would edit it.
Feel free to delete if it is the wrong place to store it.

### CODE REVIEW

**Comment by GrazianoCapelli** [comment]
PS: I hope this is the right place to request the pull.
If not, please tell me where to post and I'll be glad to move it in the right repo.

**Comment by michael63-osm** [comment]
You found the perfect location for the pull request. Just be a little patient as we are all volunteers and take care of this project in our spare time - and I was travelling. I should be able to integrate this by the weekend.

**Comment by GrazianoCapelli** [comment]
Perfect.

**Comment by GrazianoCapelli** [comment]
We understand perfectly: also BasicAirData is made by volunteers, we use our spare time to take care of it.

**Comment by michael63-osm** [comment]
Thanks for the update!

**Comment by GrazianoCapelli** [comment]
To date only the English version of the _BasicAirData GPS Logger_ article is published (with related updated images), but the page in other languages describe the old way to work.
As a result, images and text are not coherent, and could create confusion for users.

Is there a way to mark the changed part of the article as untranslated in Transifex, in order to report to translators that some paragraphs would need a review?

Thanks.

**Comment by michael63-osm** [comment]
Thank you for notifying us - there was a glitch in updating the English source. I fixed this now, updated the German translation and will pull it over to LearnOSM tonight. 

We have no influence on how quickly other languages will be translated - Transifex clearly shows translation quota for the different sources, interested people can see where work is left to be done. But as with LearnOSM itself almost everyone does the work in his/her spare time so we will have to wait.

**Comment by GrazianoCapelli** [comment]
Perfect, thanks again.
I taken the opportunity to update italian translation too.

**Comment by michael63-osm** [comment]
I just pushed the updated contents in Dutch, German and Italian to the website.

**Pull request merged**
